//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASE.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Texts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Texts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ASE.Properties.Texts", typeof(Texts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done!.
        /// </summary>
        public static string Common_Message_Done_Message {
            get {
                return ResourceManager.GetString("Common_Message_Done_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        public static string Common_Message_Done_Title {
            get {
                return ResourceManager.GetString("Common_Message_Done_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown error occured..
        /// </summary>
        public static string Common_Message_Error_Message {
            get {
                return ResourceManager.GetString("Common_Message_Error_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured.
        ///{0}: {1}
        ///Please contact the developer..
        /// </summary>
        public static string Common_Message_Error_MessageDebug {
            get {
                return ResourceManager.GetString("Common_Message_Error_MessageDebug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Common_Message_Error_Title {
            get {
                return ResourceManager.GetString("Common_Message_Error_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About ASE....
        /// </summary>
        public static string MainWindow_Button_AboutASE {
            get {
                return ResourceManager.GetString("MainWindow_Button_AboutASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXECUTE.
        /// </summary>
        public static string MainWindow_Button_ExecuteTask {
            get {
                return ResourceManager.GetString("MainWindow_Button_ExecuteTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOAD.
        /// </summary>
        public static string MainWindow_Button_LoadSave {
            get {
                return ResourceManager.GetString("MainWindow_Button_LoadSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string MainWindow_Button_RefreshProfiles {
            get {
                return ResourceManager.GetString("MainWindow_Button_RefreshProfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string MainWindow_Button_RefreshSaves {
            get {
                return ResourceManager.GetString("MainWindow_Button_RefreshSaves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string MainWindow_Label_SaveInfoDate {
            get {
                return ResourceManager.GetString("MainWindow_Label_SaveInfoDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dir.
        /// </summary>
        public static string MainWindow_Label_SaveInfoDir {
            get {
                return ResourceManager.GetString("MainWindow_Label_SaveInfoDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string MainWindow_Label_SaveInfoName {
            get {
                return ResourceManager.GetString("MainWindow_Label_SaveInfoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT PROFILE.
        /// </summary>
        public static string MainWindow_Label_SelectProfile {
            get {
                return ResourceManager.GetString("MainWindow_Label_SelectProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT SAVE.
        /// </summary>
        public static string MainWindow_Label_SelectSave {
            get {
                return ResourceManager.GetString("MainWindow_Label_SelectSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT TASK.
        /// </summary>
        public static string MainWindow_Label_SelectTask {
            get {
                return ResourceManager.GetString("MainWindow_Label_SelectTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ** How to apply CC data **
        ///1. Run &apos;Apply CC Data&apos;
        ///2. Open the received CC data file (*.ddd)
        ///
        ///** NOTE **
        ///- Applying the data won&apos;t affect existing profile and saves. It will simply add new saves to the profile.
        ///- When a vehicle is added with this utility, they&apos;re in a very unstable state because they&apos;re not placed in a garage. Therefore, when the event is concluded, MAKE SURE TO RUN &apos;Delete all CC saves&apos;!.
        /// </summary>
        public static string Task_SpecialCCTask_HowToApply {
            get {
                return ResourceManager.GetString("Task_SpecialCCTask_HowToApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ---- Application ----.
        /// </summary>
        public static string Task_SpecialCCTask_List_01Application {
            get {
                return ResourceManager.GetString("Task_SpecialCCTask_List_01Application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply CC Data to this profile.
        /// </summary>
        public static string Task_SpecialCCTask_List_02Apply {
            get {
                return ResourceManager.GetString("Task_SpecialCCTask_List_02Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete all CC saves in this profile.
        /// </summary>
        public static string Task_SpecialCCTask_List_03Delete {
            get {
                return ResourceManager.GetString("Task_SpecialCCTask_List_03Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ---- Generation ----.
        /// </summary>
        public static string Task_SpecialCCTask_List_04Generation {
            get {
                return ResourceManager.GetString("Task_SpecialCCTask_List_04Generation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Active Vehicle.
        /// </summary>
        public static string Task_SpecialCCTask_List_05ExportVehicle {
            get {
                return ResourceManager.GetString("Task_SpecialCCTask_List_05ExportVehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compile CC Data.
        /// </summary>
        public static string Task_SpecialCCTask_List_06Compile {
            get {
                return ResourceManager.GetString("Task_SpecialCCTask_List_06Compile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DLL Injection (Developer only).
        /// </summary>
        public static string Task_SpecialCCTask_List_07DLLInjection {
            get {
                return ResourceManager.GetString("Task_SpecialCCTask_List_07DLLInjection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ASE CC Tool.
        /// </summary>
        public static string Task_SpecialCCTask_List_Title {
            get {
                return ResourceManager.GetString("Task_SpecialCCTask_List_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect Trailer Here.
        /// </summary>
        public static string TaskDefs_ConnectTrailerInstantly_1 {
            get {
                return ResourceManager.GetString("TaskDefs_ConnectTrailerInstantly_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forces the assigned trailer to connect to the truck immediately. Make sure there&apos;s enough space for the straight trailer behind!.
        /// </summary>
        public static string TaskDefs_ConnectTrailerInstantly_2 {
            get {
                return ResourceManager.GetString("TaskDefs_ConnectTrailerInstantly_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decode Player Position.
        /// </summary>
        public static string TaskDefs_DecodePosition_1 {
            get {
                return ResourceManager.GetString("TaskDefs_DecodePosition_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decodes the shared player position data in the current clipboard to a human-readable decimal format. Units are in meters..
        /// </summary>
        public static string TaskDefs_DecodePosition_2 {
            get {
                return ResourceManager.GetString("TaskDefs_DecodePosition_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute VPS.
        /// </summary>
        public static string TaskDefs_ExecuteVPS_1 {
            get {
                return ResourceManager.GetString("TaskDefs_ExecuteVPS_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute VPS(Vehicle Placement Script) in your clipboard. Copy the full script into clipboard before executing this task..
        /// </summary>
        public static string TaskDefs_ExecuteVPS_2 {
            get {
                return ResourceManager.GetString("TaskDefs_ExecuteVPS_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify EXP.
        /// </summary>
        public static string TaskDefs_ExpSet_1 {
            get {
                return ResourceManager.GetString("TaskDefs_ExpSet_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify the desired amount of experience points (EXP)..
        /// </summary>
        public static string TaskDefs_ExpSet_2 {
            get {
                return ResourceManager.GetString("TaskDefs_ExpSet_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repair All.
        /// </summary>
        public static string TaskDefs_FixEverything_1 {
            get {
                return ResourceManager.GetString("TaskDefs_FixEverything_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repairs all trucks and trailers in the current savegame.
        ///
        ///1.49 Warning - This will even repair trucks in used truck dealer!.
        /// </summary>
        public static string TaskDefs_FixEverything_2 {
            get {
                return ResourceManager.GetString("TaskDefs_FixEverything_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Navigation.
        /// </summary>
        public static string TaskDefs_ImportNavigation_1 {
            get {
                return ResourceManager.GetString("TaskDefs_ImportNavigation_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imports the shared navigation waypoints from clipboard..
        /// </summary>
        public static string TaskDefs_ImportNavigation_2 {
            get {
                return ResourceManager.GetString("TaskDefs_ImportNavigation_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Player Position.
        /// </summary>
        public static string TaskDefs_ImportPosition_1 {
            get {
                return ResourceManager.GetString("TaskDefs_ImportPosition_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imports the shared player position data to incorporate it into the current savegame..
        /// </summary>
        public static string TaskDefs_ImportPosition_2 {
            get {
                return ResourceManager.GetString("TaskDefs_ImportPosition_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify Cash.
        /// </summary>
        public static string TaskDefs_MoneySet_1 {
            get {
                return ResourceManager.GetString("TaskDefs_MoneySet_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify the desired amount of cash in the game..
        /// </summary>
        public static string TaskDefs_MoneySet_2 {
            get {
                return ResourceManager.GetString("TaskDefs_MoneySet_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reduce Position Code.
        /// </summary>
        public static string TaskDefs_ReducePosition_1 {
            get {
                return ResourceManager.GetString("TaskDefs_ReducePosition_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reduce the length of position code by removing trailer position data. These are not necessary as long as you create the code with enough space behind..
        /// </summary>
        public static string TaskDefs_ReducePosition_2 {
            get {
                return ResourceManager.GetString("TaskDefs_ReducePosition_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refuel current vehicle.
        /// </summary>
        public static string TaskDefs_RefuelReal_1 {
            get {
                return ResourceManager.GetString("TaskDefs_RefuelReal_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set the fuel(or battery) level of current truck to 100%..
        /// </summary>
        public static string TaskDefs_RefuelReal_2 {
            get {
                return ResourceManager.GetString("TaskDefs_RefuelReal_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infinite fuel current vehicle.
        /// </summary>
        public static string TaskDefs_RefuelUnreal_1 {
            get {
                return ResourceManager.GetString("TaskDefs_RefuelUnreal_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set the fuel(or battery) level of current truck to 1000x of the fuel tank. You must disable realistic fuel consumption in the game settings..
        /// </summary>
        public static string TaskDefs_RefuelUnreal_2 {
            get {
                return ResourceManager.GetString("TaskDefs_RefuelUnreal_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjust Trailer Cargo Mass.
        /// </summary>
        public static string TaskDefs_SetCargoMass_1 {
            get {
                return ResourceManager.GetString("TaskDefs_SetCargoMass_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify the cargo mass of the assigned trailer according to your preference..
        /// </summary>
        public static string TaskDefs_SetCargoMass_2 {
            get {
                return ResourceManager.GetString("TaskDefs_SetCargoMass_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share Navigation.
        /// </summary>
        public static string TaskDefs_ShareNavigation_1 {
            get {
                return ResourceManager.GetString("TaskDefs_ShareNavigation_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shares the current navigation waypoints with others by copying it to the clipboard..
        /// </summary>
        public static string TaskDefs_ShareNavigation_2 {
            get {
                return ResourceManager.GetString("TaskDefs_ShareNavigation_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share Player Position.
        /// </summary>
        public static string TaskDefs_SharePosition_1 {
            get {
                return ResourceManager.GetString("TaskDefs_SharePosition_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicates the position of the player&apos;s truck and trailer, allowing you to share it with others by copying it to the clipboard..
        /// </summary>
        public static string TaskDefs_SharePosition_2 {
            get {
                return ResourceManager.GetString("TaskDefs_SharePosition_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event CC Tools.
        /// </summary>
        public static string TaskDefs_SpecialCCTask_1 {
            get {
                return ResourceManager.GetString("TaskDefs_SpecialCCTask_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please read the manual inside before using it! Otherwise the consequences can be disastrous!.
        /// </summary>
        public static string TaskDefs_SpecialCCTask_2 {
            get {
                return ResourceManager.GetString("TaskDefs_SpecialCCTask_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teleport to Job Destination.
        /// </summary>
        public static string TaskDefs_TeleportToCargo_1 {
            get {
                return ResourceManager.GetString("TaskDefs_TeleportToCargo_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this to teleport to any company as you want in TruckersMP by using Job Dispatcher. Refer to &apos;ase&apos; channel in MCG Discord for how-to-use..
        /// </summary>
        public static string TaskDefs_TeleportToCargo_2 {
            get {
                return ResourceManager.GetString("TaskDefs_TeleportToCargo_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Truck Engine.
        /// </summary>
        public static string TaskDefs_TruckEngineSet_1 {
            get {
                return ResourceManager.GetString("TaskDefs_TruckEngineSet_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switches the truck&apos;s engine to one of the available options..
        /// </summary>
        public static string TaskDefs_TruckEngineSet_2 {
            get {
                return ResourceManager.GetString("TaskDefs_TruckEngineSet_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlock all UI.
        /// </summary>
        public static string TaskDefs_UnlockScreens_1 {
            get {
                return ResourceManager.GetString("TaskDefs_UnlockScreens_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enables locked GUIs, including skills, for new profiles. Some normally disabled GUIs may also be enabled..
        /// </summary>
        public static string TaskDefs_UnlockScreens_2 {
            get {
                return ResourceManager.GetString("TaskDefs_UnlockScreens_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Sharing.
        /// </summary>
        public static string TaskDefs_VehicleSharing_1 {
            get {
                return ResourceManager.GetString("TaskDefs_VehicleSharing_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can use this tool to easily share and import trucks and trailers without worrying about collisions and errors..
        /// </summary>
        public static string TaskDefs_VehicleSharing_2 {
            get {
                return ResourceManager.GetString("TaskDefs_VehicleSharing_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Own Job Vehicle.
        /// </summary>
        public static string TaskDefs_VehicleStealer_1 {
            get {
                return ResourceManager.GetString("TaskDefs_VehicleStealer_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can steal the trailer or truck from the job. If the trailer is yours, you can steal the cargo loaded in it..
        /// </summary>
        public static string TaskDefs_VehicleStealer_2 {
            get {
                return ResourceManager.GetString("TaskDefs_VehicleStealer_2", resourceCulture);
            }
        }
    }
}
